# Generated by Django 5.1.1 on 2024-10-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('is_found', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
