# Generated by Django 5.1.1 on 2024-12-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_category_item_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(default='SCD', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(default='dwd', max_length=50),
            preserve_default=False,
        ),
    ]
