# Generated by Django 5.1.1 on 2024-12-05 22:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_item_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='item',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
